# Generated by Django 4.0 on 2023-04-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('address', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('link_google_maps', models.CharField(default='', max_length=255)),
                ('cellphone1', models.CharField(max_length=20)),
                ('cellphone2', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Centro de ayuda',
                'verbose_name_plural': 'Centros de ayuda',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonaParaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Número Ayuda OMAK',
                'verbose_name_plural': 'Números de ayuda OMAK',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioAtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, default='', max_length=100)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('fecha_atendido', models.DateTimeField(auto_now=True)),
                ('ci', models.CharField(blank=True, default='', max_length=20)),
                ('celular', models.IntegerField(null=True)),
                ('motivo_consulta', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Usuario atendido',
                'verbose_name_plural': 'Usuarios atendidos',
            },
        ),
        migrations.CreateModel(
            name='UsuariosDeApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('ci', models.CharField(max_length=20)),
                ('celular', models.IntegerField()),
                ('user_id', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Usuario de la aplicación',
                'verbose_name_plural': 'Usuarios de la aplicación',
            },
        ),
        migrations.CreateModel(
            name='NumerosAyudaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('parentesco', models.CharField(choices=[('Otro', 'Otro'), ('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Hermana', 'Hermana')], default='OTRO', max_length=100)),
                ('otro_parentesco', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.IntegerField()),
                ('usuario_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_auxilio', to='users.usuariosdeapp')),
            ],
            options={
                'verbose_name': 'Número de auxilio',
                'verbose_name_plural': 'Números de auxilio para usuario',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarioatendido')),
            ],
            options={
                'verbose_name': 'Registro de Caso',
                'verbose_name_plural': 'Registro de casos',
                'ordering': ['created_at'],
            },
        ),
    ]
