# Generated by Django 4.0 on 2023-04-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosdeapp',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usuariosdeapp',
            name='identifier',
            field=models.CharField(default=3, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
