# Generated by Django 4.0 on 2023-05-11 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuariosdeapp_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioatendido',
            name='usuario_applicacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuariosdeapp'),
        ),
    ]
